//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtResourceGrabber {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BtResourceGrabber.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [G] 的本地化字符串。
        /// </summary>
        internal static string ByPassProxyTabText {
            get {
                return ResourceManager.GetString("ByPassProxyTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {\rtf1\ansi\ansicpg936\deff0\nouicompat\deflang1033\deflangfe2052{\fonttbl{\f0\fnil\fcharset134 \&apos;ce\&apos;a2\&apos;c8\&apos;ed\&apos;d1\&apos;c5\&apos;ba\&apos;da;}{\f1\fnil\fcharset2 Symbol;}}
        ///{\colortbl ;\red155\green0\blue211;\red0\green77\blue187;}
        ///{\*\generator Riched20 10.0.10011}\viewkind4\uc1 
        ///\pard\sl240\slmult1\qc\cf1\b\f0\fs28\lang2052\&apos;a1\&apos;b6\&apos;b1\&apos;c8\&apos;c4\&apos;bf\&apos;d3\&apos;e3\&apos;a1\&apos;b7 \&apos;d3\&apos;c3\&apos;bb\&apos;a7\&apos;d0\&apos;ad\&apos;d2\&apos;e9\par
        ///
        ///\pard\fi568\sl240\slmult1\cf2\fs22\&apos;c8\&apos;e7\&apos;b9\&apos;fb\&apos;c4\&apos;fa\&apos;ca\&apos;b9\&apos;d3\&apos;c3\&apos;b1\&apos;be\&apos;c8\&apos;ed\&apos;bc\&apos;fe\&apos;a3\&apos;ac\&apos;d4\&apos;f2 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 综合搜索 的本地化字符串。
        /// </summary>
        internal static string MultipleSearch {
            get {
                return ResourceManager.GetString("MultipleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [^] 的本地化字符串。
        /// </summary>
        internal static string SupportSortTabText {
            get {
                return ResourceManager.GetString("SupportSortTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [汉] 的本地化字符串。
        /// </summary>
        internal static string SupportUnicodeTabText {
            get {
                return ResourceManager.GetString("SupportUnicodeTabText", resourceCulture);
            }
        }
    }
}
